doctrine:
    dbal:
        # url does not work with socket path :( 
        #url: '%env(resolve:DATABASE_URL)%'
        driver:   pdo_pgsql
        host:     '%env(resolve:DB_HOST)%'
        port:     '%env(resolve:DB_PORT)%'
        dbname:   '%env(resolve:DB_DBNAME)%'
        user:     '%env(resolve:DB_USER)%'
        password: '%env(resolve:DB_PASSWORD)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '%env(resolve:DB_VERSION)%'
        mapping_types:
            _int4: integer
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        dql:
            string_functions:
                JSON_CONTAINS: 'App\Doctrine\Functions\Contains'
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
