# As of Symfony 5.1, deprecations are logged in the dedicated "deprecation" channel when it exists
# no deprecations log on production
monolog:
    channels: [deprecation]
    handlers:
        deprecation:
            type: "null"
            channels: [deprecation]
